import type { ComponentProps } from "react";
import { codeToHtml } from "shiki";
import { cn } from "@/lib/cn";

// ── Sub-components ────────────────────────────────────────────────────────────

function CodeBlockRoot({
	className,
	children,
	...props
}: ComponentProps<"div">) {
	return (
		<div
			className={cn(
				"overflow-hidden border border-border-primary bg-bg-input",
				className,
			)}
			{...props}
		>
			{children}
		</div>
	);
}

function CodeBlockHeader({
	className,
	children,
	...props
}: ComponentProps<"div">) {
	return (
		<div
			className={cn(
				"flex h-10 items-center justify-between border-b border-border-primary px-4",
				className,
			)}
			{...props}
		>
			<div className="flex items-center gap-1.5">
				<span className="size-2.5 rounded-full bg-accent-red" />
				<span className="size-2.5 rounded-full bg-accent-amber" />
				<span className="size-2.5 rounded-full bg-accent-green" />
			</div>
			{children}
		</div>
	);
}

type CodeBlockBodyProps = {
	code: string;
	lang?: string;
	className?: string;
};

async function CodeBlockBody({
	code,
	lang = "javascript",
	className,
}: CodeBlockBodyProps) {
	const html = await codeToHtml(code, {
		lang,
		theme: "vesper",
	});

	return (
		<div
			className={cn(
				"overflow-x-auto p-4 text-[13px] [&_pre]:m-0 [&_pre]:bg-transparent! [&_pre]:p-0",
				className,
			)}
			// biome-ignore lint/security/noDangerouslySetInnerHtml: safe, output is generated by shiki
			dangerouslySetInnerHTML={{ __html: html }}
		/>
	);
}

// ── Namespace export ──────────────────────────────────────────────────────────

const CodeBlock = {
	Root: CodeBlockRoot,
	Header: CodeBlockHeader,
	Body: CodeBlockBody,
};

export type { CodeBlockBodyProps };
export { CodeBlock };
